"""empty message

Revision ID: 18797b9715d3
Revises: cf5dbee949a5
Create Date: 2021-12-16 12:29:00.149808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18797b9715d3"
down_revision = "cf5dbee949a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
